version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.6.1
jobs:

  lint:
    docker:
    - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip3 install tox
      - run: tox -e lint

  test_python:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install MPI
          command: |
            sudo apt-get update
            sudo apt-get install libopenmpi3
            sudo pip3 install tox
      - run:
          name: run tests
          command: |
            tox -e test -e test_no_extras


workflows:
  version: 2
  tagged-build:
    jobs:
      - lint:
          filters:
            tags:
              only: /^v.*/
      - test_python:
          filters:
            tags:
              only: /^v.*/
